source 'https://rubygems.org'

gem 'cocoapods', '~> 1.14'
gem 'fastlane', '~> 2.219'
gem 'rake', '~> 12.3'
gem 'rubocop', '~> 1.18'
gem 'xcpretty-travis-formatter', '~> 1.0'
gem 'fastlane-plugin-wpmreleasetoolkit', '~> 9.2'
gem 'fastlane-plugin-sentry', '~> 1.14'
gem 'fastlane-plugin-appcenter', '~> 1.11'
