# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.0
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-14.2

# This is the default pipeline – it will build and test the app
steps:
  - label: "🛠 App Store Upload"
    command: .buildkite/commands/build-and-upload-release.sh
    priority: 1
    env: *common_env
    plugins: *common_plugins
